---
title: "Background Points"
csl: Methods.csl
output:
  html_document:
    css: zoon.css
    theme: lumen
    toc: yes
    toc_float:
      collapsed: no
      toc_depth: 4
bibliography: bibliography.bib
output: html_document
---

## Introduction

Many species distribution model (SDM) analyses make use of presence-only datasets. These datasets often stem from historical or museum records, citizen science, and other, often opportunistic, unstructured surveys. Most modelling methods, however, are not compatible with presence-only datasets. In lieu of proper absence observation records we need to make use of background, or pseudo-absence, points. Depending on the viewpoint of the modeller and the modelling method being used, these can be interpreted as pseudo-absences, samples of the environmental background, or integration points (**REF**, see forum post). For example, MaxEnt, one of the most widely used SDM methods, uses background points to sample the environmental predictor space. Yet MaxEnt can be considered equivalent to a poisson-point process model where they are considered integration points.

**Logistic regression: treated as pseudo-absences?**

Regardless of interpretation, when using an SDM for presence-background data we need to make a decision about *how* to generate our background points, and *how many* do we need? These choices can have important impacts on our SDM.

## How many background points?

The number of background points sampled has generally been selected *ad hoc*. Quantities between 1,000 - 10,000 are frequently seen in the literature. A study by Barbet-Massin (**REF**) found that different modelling methods performed best with different quantities of background points (e.g. 10,000 for regression-based SDMs).

Where background points are interpreted as samples of the environmental space, however, then *ad hoc* quantities may seem less appropriate. Here we need to generate enough background points to adequately sample the environmental covariate space. Thus the roughness of covariate space largely defines the number of background points required; more variability = more points required (**right?**). In theory an infinitely large number of background points would best approximate this covariate space, but computationally this is generally not a feasible approach.

**Need closing sentence**

## How to generate background points?

+ Random
+ Bias layer
+ Targetted background

## Conclusion
