---
title: "Introduction to SDMs"
author: "zoontutorials team"
date: "6 February 2017"
output: html_document
---

# Introduction
* Why do SDMs?
  + maps (prediction) vs. ecology (inference)
* Types of SDMs
  + correlative vs. mechanistic models
  + multispecies models
* brief discussion of the limitations of the method used here
* conceptual map of workflow steps

# Basic SDM Workflow
* This section will include the steps, and the r script, with visuals for the steps (head of data, model formula, output visual)

```{r this is a chunk of code}
library(zoon)
```


# Detailed SDM Workflow
## Step 1. Occurrence
* types of occurrence data
  + presence only
  + presence-absence
* limitations of po
* sourced from internet vs. your own data

## Step 2. Covariates
* gridded covariates
* discuss concept of niche space vs. geographic space
  + include a graphical representation of this?
* limitations 
  + mobile species
  + garbage in, garbage out
  + extrapolation

## Step 3. Process
* how to deal with pseudoabsence data

## Step 4. Model

## Step 5. Output
* types of output
* interpreting outputs

# Conclusion


