---
title: "Model Validation"
output:
  html_document:
    css: zoon.css
    toc: yes
    toc_float:
      collapsed: false
      toc_depth: 4
    theme: lumen
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Model Validation}
  %\VignetteEncoding{UTF-8}
---

<hr>

## Is my model any good?

Not all species distribution models are created equal. The ease of fitting species distribution models means that sometimes we use them willy-nilly without questioning the results, how accurate they are, and whether the mdoel is 'fit for purpose'. We need first to know if your model is a reaonsable representtion of reality. What is reasonable is still being debated and there's no hard line in the sand, so far.

Bearing in mind that all models are just that: models. They won't perfectly represent truth but they may still be useful. It's important to consider if our model is good *enough* for it's purpose, rather than if it is *good* in absolute terms. This means we're not validatin ght emoel as representative of truth, per se, by vaidating it as *fit for purpose*. Model evaluation is the process of checking our model outputs to determine if they are a close enough representation of reality for the purpose you're using it for.

In this best practice guide, we will talk about the different ways of evaluating a model (or set of models), when we might choose one methods over an another, and lastly, how to implememnt these model evaluation methods in `zoon`. We'll use one example throughout to demonstrate the concepts and how to use `zoon` for simple and reporducible model evaluation

Need to choose between models

## What is model evaluation?

There's many different ways to do model evalation and which way we choose will depend on the data we have available, 


What method of model evaluation you choose depends on what you ant to use th emodel for. If you ony want to accuratley map the here and now, you won't neccessaruly mind about over-fitting. Howveer, if you need to predict to a new time or place, or you want to identify generalisable patterns, you need your model to fin dthe pattern among the noise - that is, you need the model not to be overfit, but still be a good descriptoin of the truth.

If you're using your model to predict to a new time or place, you'll need to assess if your model can do that.

If you're only trying to get an accurate picture of here and now, you need to know whether your model has fit your data accuratley.

If you only want to make ecological inference - to find general patterns in ecology - you'll still be concerned


### The bare minimum

Let's first run through what we at zoon believe is the bare minimum. Some of what follows we'll do just as part of interpretting our results, but it's good to be cogniscent that we're looking to question the model and it's accuracy, rather than accepting the printed map or response curve as gospel truth.

Check maps match data (interactive map)

One can go a little bit further in evaluating model fit by plotting species repsonse curves where available (response curves)

For parametric models, check coefficients make sense (go the same way as data, giev back sensible results) (coefficient plot)

### Internal evalution

The next step up in the model evaluation game is internal evaluation. Internal evaluation checks if our model is a good description of the data we fit it with.

#### Deviance and Variance

R-squared (variance explained)

Deviance

#### Information criteria

Information criteria build on deviance measures by penalising models for additional covariates. That is, they select for accurate and *parimsoneous*models.

### Cross-validation

Model cross-validation is the gold standard of model evalution in species distritbuion models. In the absence of a independently dataset, that is.

There's many way to do cross-validation and again it depends on what aspect of model performance we want to check.

Cross-validation works as follows - you iteratively split the data into a test and training dataset. The model is fit (or 'trained') with the traiing dataset and evaluated with the test dataset.

#### K-fold

#### Bootstrap

#### Exrapolation in space

Want to do if need to predict range shift or to a new location. Olden (ref) refer to this as the transferability of the model in space. And you do it by 

Can your model predict extremes? Can it extrpolate.

#### The controversial AUC

#### Specificity

#### Selectivity

## How do I know if my model is over-fitted?

...

## Conclusion





